/**
 * Credential Entity
 *
 * Represents a registered passkey in the database.
 *
 * Relations:
 * - ManyToOne with User: A passkey belongs to a user
 *
 * @module entities/credential.entity
 */
import {
  Column,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from "typeorm";
import { User } from "./user.entity";

@Entity("credentials")
export class Credential {
  /**
   * Unique passkey ID (UUID)
   * Automatically generated by PostgreSQL
   */
  @PrimaryGeneratedColumn("uuid")
  id: string;

  /**
   * Unique passkey identifier (credential ID)
   *
   * Format: base64url
   * Used by WebAuthn to identify the passkey during authentication.
   * Corresponds to the ID returned by the authenticator during registration.
   */
  @Column()
  credentialId: string;

  /**
   * Passkey public key
   *
   * Format: base64
   * Used to verify signatures during authentication.
   * The private key remains on the authenticator and is never transmitted.
   */
  @Column("text")
  publicKey: string;

  /**
   * Anti-replay counter
   *
   * Incremented each time the passkey is used.
   * The backend verifies that the counter always increases to detect
   * replay attacks (reuse of a signature).
   */
  @Column()
  counter: number;

  /**
   * Device type on which the passkey was registered
   *
   * Examples: "iOS Device", "Android Device", "Desktop"
   * Used for display in the user interface.
   */
  @Column()
  deviceType: string;

  /**
   * Indicates if the passkey is backed up
   *
   * true: The passkey is backed up (iCloud Keychain, Google Password Manager, etc.)
   * false: The passkey is not backed up (physical security key)
   *
   * Backed up passkeys can be restored on other devices.
   */
  @Column({ nullable: true })
  backedUp: boolean;

  /**
   * ManyToOne relation with User
   * A passkey belongs to a user
   */
  @ManyToOne(() => User, (user) => user.credentials)
  @JoinColumn({ name: "userId" })
  user: User;

  /**
   * ID of the user who owns the passkey
   * Foreign key to the users table
   */
  @Column()
  userId: string;

  /**
   * Passkey creation date
   * Automatically generated on registration
   */
  @Column({ type: "timestamp", default: () => "CURRENT_TIMESTAMP" })
  createdAt: Date;
}
