/**
 * User Entity
 *
 * Represents a user in the database.
 *
 * Relations:
 * - OneToMany with Credential: A user can have multiple passkeys
 *
 * @module entities/user.entity
 */
import { Column, Entity, OneToMany, PrimaryGeneratedColumn } from "typeorm";
import { Credential } from "./credential.entity";

@Entity("users")
export class User {
  /**
   * Unique user ID (UUID)
   * Automatically generated by PostgreSQL
   */
  @PrimaryGeneratedColumn("uuid")
  id: string;

  /**
   * User's first name
   */
  @Column()
  firstName: string;

  /**
   * User's last name
   */
  @Column()
  lastName: string;

  /**
   * User's email (unique)
   * Used for login and as WebAuthn identifier
   */
  @Column({ unique: true })
  email: string;

  /**
   * Password hashed with bcrypt
   * Should never be returned in API responses
   */
  @Column()
  password: string;

  /**
   * OneToMany relation with passkeys
   * A user can have multiple passkeys (one per device)
   */
  @OneToMany(() => Credential, (credential) => credential.user)
  credentials: Credential[];

  /**
   * Account creation date
   * Automatically generated on creation
   */
  @Column({ type: "timestamp", default: () => "CURRENT_TIMESTAMP" })
  createdAt: Date;
}
